---
- name: Deploy a kpatch demo environment
  hosts: "{{ vm_name }}"
  serial: 1

  tasks:
  - name: Create our SA Labs / Demos directories for our tools and scripts
    file:
      path: "{{ item }}"
      state: directory
      mode: "u=rwx,g=wx,o=rwx"
    with_items:
      - /root/tools

  - name: Copy the files needed for this Lab / Demo
    copy:
      src: ./files/
      dest: /root/tools/
      owner: root
      group: root
      mode: '0755'

  - name: Set Hostname on "{{ vm_name }}"
    hostname:
      name: "{{ vm_name }}"

  - name: Set grub to default to the old kernel on boot so we are vulnerable for the exploit
    shell: /usr/sbin/grubby --set-default-index=1

  - name: Subscribe to our Satellite using our activation key
    redhat_subscription:
      state: present
      activationkey: RHEL_81
      org_id: Shadow_Man
    ignore_errors: true

  - name: Reboot the machine
    reboot:
